# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value





services:

    guzzle_client:
        class: GuzzleHttp\Client

    api.response_factory:
        class: AppBundle\Api\ResponseFactory


    jwt_token_authenticator:
      class: AppBundle\Security\JwtTokenAuthenticator
      autowire: true

    api_exception_subscriber:
        class: AppBundle\EventListener\ApiExceptionSubscriber
        arguments: ['%kernel.debug%', '@api.response_factory', '@logger']
        tags:
            - { name: kernel.event_subscriber }

    user_service:
       class: AppBundle\Service\UserService
       arguments: ['@doctrine.orm.default_entity_manager','@security.password_encoder','@lexik_jwt_authentication.encoder.default']


    database_perger_configurator:
       class: Doctrine\Common\DataFixtures\Purger\ORMPurger
       arguments: ['@doctrine.orm.default_entity_manager']

    database_perger:
       class: AppBundle\Service\DatabasePurger
       arguments: ['@database_perger_configurator','%kernel.environment%']

    alice.processor.user:
        class: AppBundle\DataFixtures\Processor\UserProcessor
        arguments:
          - '@security.password_encoder'
        tags: [ { name: fidry_alice_data_fixtures.processor } ]


